apiVersion: apps/v1
kind: Deployment
metadata:
  name: insuranceapp-eta-deploy
  labels:
    app: insuranceapp-eta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: insuranceapp-eta-app
  template:
    metadata:
      labels:
        app: insuranceapp-eta-app
    spec:
      containers:
      - name: insuranceapp-eta-container
        image: revati21/insuranceapp-eta-app
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: insuranceapp-eta-np-service
  labels:
    app: insuranceapp-eta-app
spec:
  selector:
    app: insuranceapp-eta-app
  type: NodePort
  ports:
  - nodePort: 31030
    port: 8081
    targetPort: 8081
